# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mailgun-ruby` gem.
# Please instead update this file by running `bin/tapioca gem mailgun-ruby`.


# source://mailgun-ruby//lib/railgun/message.rb#6
module Mail; end

# source://mailgun-ruby//lib/railgun/message.rb#8
class Mail::Message
  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_headers; end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_headers=(_arg0); end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_options; end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_options=(_arg0); end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_recipient_variables; end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_recipient_variables=(_arg0); end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_template_variables; end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_template_variables=(_arg0); end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_variables; end

  # Attributes to hold Mailgun-specific information
  #
  # source://mailgun-ruby//lib/railgun/message.rb#11
  def mailgun_variables=(_arg0); end
end

# Module for interacting with the sweet Mailgun API.
#
# See the Github documentation for full examples.
#
# source://mailgun-ruby//lib/mailgun/version.rb#2
module Mailgun
  class << self
    # Returns the value of attribute api_host.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def api_host; end

    # Sets the attribute api_host
    #
    # @param value the value to set the attribute api_host to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def api_host=(_arg0); end

    # Returns the value of attribute api_key.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def api_key; end

    # Sets the attribute api_key
    #
    # @param value the value to set the attribute api_key to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def api_key=(_arg0); end

    # Returns the value of attribute api_version.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def api_version; end

    # Sets the attribute api_version
    #
    # @param value the value to set the attribute api_version to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def api_version=(_arg0); end

    # @yield [_self]
    # @yieldparam _self [Mailgun] the object that the method was called on
    #
    # source://mailgun-ruby//lib/mailgun.rb#42
    def config; end

    # @yield [_self]
    # @yieldparam _self [Mailgun] the object that the method was called on
    #
    # source://mailgun-ruby//lib/mailgun.rb#38
    def configure; end

    # Returns the value of attribute domain.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def domain; end

    # Sets the attribute domain
    #
    # @param value the value to set the attribute domain to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def domain=(_arg0); end

    # Returns the value of attribute mailgun_host.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def mailgun_host; end

    # Sets the attribute mailgun_host
    #
    # @param value the value to set the attribute mailgun_host to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def mailgun_host=(_arg0); end

    # Returns the value of attribute protocol.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def protocol; end

    # Sets the attribute protocol
    #
    # @param value the value to set the attribute protocol to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def protocol=(_arg0); end

    # Returns the value of attribute proxy_url.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def proxy_url; end

    # Sets the attribute proxy_url
    #
    # @param value the value to set the attribute proxy_url to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def proxy_url=(_arg0); end

    # Returns the value of attribute test_mode.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def test_mode; end

    # Sets the attribute test_mode
    #
    # @param value the value to set the attribute test_mode to.
    #
    # source://mailgun-ruby//lib/mailgun.rb#29
    def test_mode=(_arg0); end
  end
end

# Mailgun::Address is a simple interface to the Email Validation API.
#
# source://mailgun-ruby//lib/mailgun/address.rb#6
class Mailgun::Address
  # @return [Address] a new instance of Address
  #
  # source://mailgun-ruby//lib/mailgun/address.rb#7
  def initialize; end

  # Given an arbitrary address, validates it based on defined checks.
  #
  # @param address [String] Email address to validate (max 512 chars.)
  #
  # source://mailgun-ruby//lib/mailgun/address.rb#14
  def validate(address, mailbox_verification = T.unsafe(nil)); end
end

# Public: Class for managing bad request 400 errors
# Inherits from Mailgun::CommunicationError
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#86
class Mailgun::BadRequest < ::Mailgun::CommunicationError
  # @return [BadRequest] a new instance of BadRequest
  #
  # source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#89
  def initialize(error_message, response); end
end

# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#87
Mailgun::BadRequest::CODE = T.let(T.unsafe(nil), Integer)

# A Mailgun::BatchMessage object is used to create a valid payload
# for Batch Sending. Batch Sending can be difficult to implement, therefore
# this code makes it dead simple to send millions of messages in batches of
# 1,000 recipients per HTTP call.
#
# For the curious, the class simply keeps track of recipient data (count,
# user variables), and fires the API payload on the 1,000th addition of a recipient.
#
# The best way to use this class is:
# 1. Build your message using the Message Builder methods.
# 2. Query your source and create an iterable list.
# 3. Iterate through your source data, and add your recipients using the
#    add_recipient() method.
# 4. Call finalize() to flush any remaining recipients and obtain/store
#    the message_ids for tracking purposes.
#
# See the Github documentation for full examples.
#
# source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#22
class Mailgun::BatchMessage < ::Mailgun::MessageBuilder
  # Public: Creates a new BatchMessage object.
  #
  # @return [BatchMessage] a new instance of BatchMessage
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#27
  def initialize(client, domain); end

  # Adds a specific type of recipient to the batch message object.
  #
  # @param recipient_type [String] The type of recipient. "to".
  # @param address [String] The email address of the recipient to add to the message object.
  # @param variables [Hash] A hash of the variables associated with the recipient. We recommend "first" and "last" at a minimum!
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#46
  def add_recipient(recipient_type, address, variables = T.unsafe(nil)); end

  # Returns the value of attribute domain.
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#24
  def domain; end

  # Always call this function after adding recipients. If less than 1000 are added,
  # this function will ensure the batch is sent.
  #
  # @return [Hash] A hash of {'Message ID' => '# of Messages Sent'}
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#62
  def finalize; end

  # Returns the value of attribute message_ids.
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#24
  def message_ids; end

  # Returns the value of attribute recipient_variables.
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#24
  def recipient_variables; end

  private

  # This method determines if it's necessary to send another batch.
  #
  # @return [Boolean]
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#72
  def any_recipients_left?; end

  # This method stores recipient variables for each recipient added, if
  # variables exist.
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#105
  def count_recipients; end

  # This method resets the message object to prepare for the next batch
  # of recipients.
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#113
  def reset_message; end

  # This method initiates a batch send to the API. It formats the recipient
  # variables, posts to the API, gathers the message IDs, then flushes that data
  # to prepare for the next batch. This method implements the Mailgun Client, thus,
  # an exception will be thrown if a communication error occurs.
  #
  # @return [Boolean]
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#85
  def send_message; end

  # This method stores recipient variables for each recipient added, if
  # variables exist.
  #
  # source://mailgun-ruby//lib/mailgun/messages/batch_message.rb#98
  def store_recipient_variables(recipient_type, address, variables); end
end

# Public constants used throughout
#
# source://mailgun-ruby//lib/mailgun/chains.rb#4
class Mailgun::Chains; end

# maximum campaign ids per message
#
# source://mailgun-ruby//lib/mailgun/chains.rb#7
Mailgun::Chains::MAX_CAMPAIGN_IDS = T.let(T.unsafe(nil), Integer)

# maximum recipients per message or batch
#
# source://mailgun-ruby//lib/mailgun/chains.rb#13
Mailgun::Chains::MAX_RECIPIENTS = T.let(T.unsafe(nil), Integer)

# maximum tags per message
#
# source://mailgun-ruby//lib/mailgun/chains.rb#10
Mailgun::Chains::MAX_TAGS = T.let(T.unsafe(nil), Integer)

# A Mailgun::Client object is used to communicate with the Mailgun API. It is a
# wrapper around RestClient so you don't have to worry about the HTTP aspect
# of communicating with our API.
#
# See the Github documentation for full examples.
#
# source://mailgun-ruby//lib/mailgun/client.rb#11
class Mailgun::Client
  # @return [Client] a new instance of Client
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#14
  def initialize(api_key = T.unsafe(nil), api_host = T.unsafe(nil), api_version = T.unsafe(nil), ssl = T.unsafe(nil), test_mode = T.unsafe(nil), timeout = T.unsafe(nil), proxy_url = T.unsafe(nil)); end

  # @return [String] client api version
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#85
  def api_version; end

  # Generic Mailgun DELETE Handler
  #
  # with. Be sure to include your domain, where necessary.
  #
  # @param resource_path [String] This is the API resource you wish to interact
  # @return [Mailgun::Response] A Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#187
  def delete(resource_path, params = T.unsafe(nil)); end

  # Disable test mode
  #
  # Reverts the test_mode flag and allows the client to send messages.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#58
  def disable_test_mode!; end

  # Enable test mode
  #
  # Prevents sending of any messages.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#51
  def enable_test_mode!; end

  # Generic Mailgun GET Handler
  #
  # @param resource_path [String] The API resource path to request, including the domain if required.
  # @param params [Hash] Optional request parameters, including query parameters and headers.
  #   - `:headers` [Hash] (optional) Custom headers for the request.
  # @param accept [String] The expected Content-Type of the response. Defaults to '*/*'.
  # @raise [CommunicationError] If the request fails, raises a communication error.
  # @return [Mailgun::Response] A response object containing the API response data.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#159
  def get(resource_path, params = T.unsafe(nil), accept = T.unsafe(nil)); end

  # Generic Mailgun POST Handler
  #
  # with. Be sure to include your domain, where necessary.
  # containing required parameters for the requested resource.
  #
  # @param resource_path [String] This is the API resource you wish to interact
  # @param data [Hash] This should be a standard Hash
  # @param headers [Hash] Additional headers to pass to the resource.
  # @return [Mailgun::Response] A Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#144
  def post(resource_path, data, headers = T.unsafe(nil)); end

  # Generic Mailgun PUT Handler
  #
  # with. Be sure to include your domain, where necessary.
  # containing required parameters for the requested resource.
  #
  # @param resource_path [String] This is the API resource you wish to interact
  # @param data [Hash] This should be a standard Hash
  # @return [Mailgun::Response] A Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#175
  def put(resource_path, data); end

  # Reset subaccount for primary usage
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#73
  def reset_subaccount; end

  # Simple Message Sending
  #
  # containing required parameters for the requested resource.
  #
  # @param working_domain [String] This is the domain you wish to send from.
  # @param data [Hash] This should be a standard Hash
  # @return [Mailgun::Response] A Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#102
  def send_message(working_domain, data); end

  # Change API key
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#63
  def set_api_key(api_key); end

  # Add subaccount id to headers
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#68
  def set_subaccount(subaccount_id); end

  # Constructs a Suppressions client for the given domain.
  #
  # @param domain [String] Domain which suppressions requests will be made for
  # @return [Mailgun::Suppressions]
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#202
  def suppressions(domain); end

  # Client is in test mode?
  #
  # @return [Boolean] Is the client set in test mode?
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#80
  def test_mode?; end

  private

  # Raises CommunicationError and stores response in it if present
  #
  # @param e [StandardException] upstream exception object
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#238
  def communication_error(e); end

  # Converts MIME string to file for easy uploading to API
  #
  # @param string [String] MIME string to post to API
  # @return [File] File object
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#212
  def convert_string_to_file(string); end

  # Generates the endpoint URL to for the API. Allows overriding
  # API endpoint, API versions, and toggling SSL.
  #
  # @param api_host [String] URL endpoint the library will hit
  # @param api_version [String] The version of the API to hit
  # @param ssl [Boolean] True, SSL. False, No SSL.
  # @return [string] concatenated URL string
  #
  # source://mailgun-ruby//lib/mailgun/client.rb#226
  def endpoint_generator(api_host, api_version, ssl); end

  # source://mailgun-ruby//lib/mailgun/client.rb#252
  def perform_data_validation(working_domain, data); end

  class << self
    # Provides a store of all the emails sent in test mode so you can check them.
    #
    # @return [Hash]
    #
    # source://mailgun-ruby//lib/mailgun/client.rb#92
    def deliveries; end
  end
end

# source://mailgun-ruby//lib/mailgun/client.rb#12
Mailgun::Client::SUBACCOUNT_HEADER = T.let(T.unsafe(nil), String)

# Public: Class for managing communications (eg http) response errors
# Inherits from Mailgun::Error
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#31
class Mailgun::CommunicationError < ::Mailgun::Error
  # Public: initialization of new error given a message and/or object
  #
  # message  - a String detailing the error
  # response - a RestClient::Response object
  #
  # @return [CommunicationError] a new instance of CommunicationError
  #
  # source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#44
  def initialize(message = T.unsafe(nil), response = T.unsafe(nil)); end

  # Public: gets HTTP status status
  #
  # source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#33
  def status; end
end

# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#37
Mailgun::CommunicationError::FORBIDDEN = T.let(T.unsafe(nil), String)

# Public: fallback if there is no response status on the object
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#36
Mailgun::CommunicationError::NOCODE = T.let(T.unsafe(nil), Integer)

# A Mailgun::Domains object is a simple CRUD interface to Mailgun Domains.
# Uses Mailgun
#
# source://mailgun-ruby//lib/mailgun/domains/domains.rb#7
class Mailgun::Domains
  # Public: creates a new Mailgun::Domains instance.
  #   Defaults to Mailgun::Client
  #
  # @return [Domains] a new instance of Domains
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#11
  def initialize(client = T.unsafe(nil)); end

  # Public: Activate a domain key for a specified authority and selector.
  #
  # domain    - [String] Name of the domain (ex. domain.com)
  # selector  - [String] The selector you want to activate for the domain key
  #
  # Returns [Hash] with message key and autority + selector data
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#286
  def activate_domain_key(domain, selector); end

  # Public: Add domain
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #     smtp_password - [String] Password for SMTP authentication
  #     spam_action   - [String] disabled, blocked or tag
  #       Disable, no spam filtering will occur for inbound messages.
  #       Block, inbound spam messages will not be delivered.
  #       Tag, messages will be tagged with a spam header. See Spam Filter.
  #     wildcard      - [Boolean] true or false Determines whether the domain will accept email for sub-domains.
  #
  # Returns [Hash] of created domain
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#73
  def add(domain, options = T.unsafe(nil)); end

  # Public: Add domain
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #     smtp_password - [String] Password for SMTP authentication
  #     spam_action   - [String] disabled, blocked or tag
  #       Disable, no spam filtering will occur for inbound messages.
  #       Block, inbound spam messages will not be delivered.
  #       Tag, messages will be tagged with a spam header. See Spam Filter.
  #     wildcard      - [Boolean] true or false Determines whether the domain will accept email for sub-domains.
  #
  # Returns [Hash] of created domain
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#74
  def add_domain(domain, options = T.unsafe(nil)); end

  # Public: Add domain
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #     smtp_password - [String] Password for SMTP authentication
  #     spam_action   - [String] disabled, blocked or tag
  #       Disable, no spam filtering will occur for inbound messages.
  #       Block, inbound spam messages will not be delivered.
  #       Tag, messages will be tagged with a spam header. See Spam Filter.
  #     wildcard      - [Boolean] true or false Determines whether the domain will accept email for sub-domains.
  #
  # Returns [Hash] of created domain
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#66
  def create(domain, options = T.unsafe(nil)); end

  # Public: Create a domain key
  #
  # options - [Hash] of
  #   signing_domain  - [String] Name of the domain (ex. domain.com)
  #   selector - [String] Selector to be used for the new domain key
  #   bits - [Integer] Key size, can be 1024 or 2048
  #   pem - [String] Private key PEM
  #
  # Returns [Hash] with message key
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#315
  def create_domain_key(options = T.unsafe(nil)); end

  # Public: Creates a new set of SMTP credentials for the defined domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   login  - [String] The user name (ex. bob.bar)
  #   password  - [String] A password for the SMTP credentials. (Length Min 5, Max 32)
  #
  # Returns [Hash] with message key
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#116
  def create_smtp_credentials(domain, options = T.unsafe(nil)); end

  # Public: Deactivate a domain key for a specified authority and selector
  #
  # domain    - [String] Name of the domain (ex. domain.com)
  # selector  - [String] The selector you want to activate for the domain key
  #
  # Returns [Hash] with message key and autority + selector data
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#299
  def deactivate_domain_key(domain, selector); end

  # Public: Delete Domain
  #
  # domain - [String] domain name to delete (ex. domain.com)
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#86
  def delete(domain); end

  # Public: Delete Domain
  #
  # domain - [String] domain name to delete (ex. domain.com)
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#87
  def delete_domain(domain); end

  # Public: Delete a domain key.
  #
  # options - [Hash] of
  #   signing_domain - [Integer] Name of the domain (ex. domain.com)
  #   selector - [String] Name of the selector
  #
  # Returns [Hash] with message key
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#327
  def delete_domain_key(options = T.unsafe(nil)); end

  # Public: Deletes the defined SMTP credentials.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # login  - [String] The user name (ex. bob.bar)
  #
  # Returns [Hash] with message and spec keys
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#143
  def delete_smtp_credentials(domain, login); end

  # Public: Get domain information
  #
  # domain - [String] Domain name to lookup
  #
  # Returns [Hash] Information on the requested domains.
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#37
  def get(domain); end

  # Public: Get domain information
  #
  # domain - [String] Domain name to lookup
  #
  # Returns [Hash] Information on the requested domains.
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#38
  def get_domain(domain); end

  # Public: Returns delivery connection settings for the defined domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  #
  # Returns [Hash] Information on the delivery connection settings
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#155
  def get_domain_connection_settings(domain); end

  # Public: Lists the domain keys for a specified signing domain / authority
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  #
  # Returns [Hash] with domain keys data
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#274
  def get_domain_keys(domain); end

  # Public: Returns total stats for a given domains
  #
  # domain    - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   event - [String] The type of the event.
  #   start - [String] The starting time. Should be in RFC 2822 or unix epoch format.
  #   end - [String] The ending date. Should be in RFC 2822 or unix epoch format
  #   resolution - [String] Can be either hour, day or month. Default: day
  #   duration - [String] Period of time with resoluton encoded
  #
  # Returns [Array] A list of domains (hash)
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#343
  def get_domain_stats(domain, options = T.unsafe(nil)); end

  # Public: Returns tracking settings for the defined domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  #
  # Returns [Hash] Information on the tracking settings
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#181
  def get_domain_tracking_settings(domain); end

  # Public: Get Domains
  #
  # limit - [Integer] Maximum number of records to return. (100 by default)
  # skip  - [Integer] Number of records to skip. (0 by default)
  #
  # Returns [Array] A list of domains (hash)
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#25
  def get_domains(options = T.unsafe(nil)); end

  # Public: Get domain information
  #
  # domain - [String] Domain name to lookup
  #
  # Returns [Hash] Information on the requested domains.
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#32
  def info(domain); end

  # Public: Get Domains
  #
  # limit - [Integer] Maximum number of records to return. (100 by default)
  # skip  - [Integer] Number of records to skip. (0 by default)
  #
  # Returns [Array] A list of domains (hash)
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#21
  def list(options = T.unsafe(nil)); end

  # Public: Delete Domain
  #
  # domain - [String] domain name to delete (ex. domain.com)
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#81
  def remove(domain); end

  # Public: Update domain
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #     spam_action   - [String] disabled, blocked or tag
  #       Disable, no spam filtering will occur for inbound messages.
  #       Block, inbound spam messages will not be delivered.
  #       Tag, messages will be tagged wtih a spam header. See Spam Filter.
  #     web_scheme    - [String] http or https
  #       Set your open, click and unsubscribe URLs to use http or https
  #     wildcard      - [Boolean] true or false Determines whether the domain will accept email for sub-domains.
  #
  # Returns [Hash] of updated domain
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#102
  def update(domain, options = T.unsafe(nil)); end

  # Public: Updates the specified delivery connection settings for the defined domain.d
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   require_tls  - [Boolean] true or false. If true - requires the message only be sent over a TLS connection
  #   skip_verification  - [Boolean] true or false. If true - the certificate and hostname will not be verified
  #     when trying to establish a TLS connection
  #
  # Returns [Hash] Information on the delivery connection settings
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#170
  def update_domain_connection_settings(domain, options = T.unsafe(nil)); end

  # Public: Change the DKIM authority for a domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   self  - [Boolean] true - the domain will be the DKIM authority for itself even
  #           if the root domain is registered on the same mailgun account
  #
  # Returns [Hash] Information on the DKIM authority
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#237
  def update_domain_dkim_authority(domain, options = T.unsafe(nil)); end

  # Public: Update the DKIM selector for a domains
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   dkim_selector  - [String] change the DKIM selector for a domain.
  #
  # Returns [Hash] with message key
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#250
  def update_domain_dkim_selector(domain, options = T.unsafe(nil)); end

  # Public: Updates the click tracking settings for a domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   active  - [Boolean] yes or no. If set to yes, links will be overwritten and pointed to our servers so we can track clicks.
  #
  # Returns [Hash] Information on the tracking click settings
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#208
  def update_domain_tracking_click_settings(domain, options = T.unsafe(nil)); end

  # Public: Updates the open tracking settings for a domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   active  - [Boolean] yes or no. If set to yes, a tracking pixel will be inserted below your HTML content.
  #   place_at_the_top  - [Boolean] yes or no. If set to yes, tracking pixel will be moved to top of your HTML content.
  #
  # Returns [Hash] Information on the tracking open settings
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#195
  def update_domain_tracking_open_settings(domain, options = T.unsafe(nil)); end

  # Public: Updates unsubscribe tracking settings for a domain.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   active  - [Boolean] true or false.
  #   html_footer  - [String] Custom HTML version of unsubscribe footer.
  #   text_footer  - [String] Custom text version of unsubscribe footer.
  #
  # Returns [Hash] Information on the tracking unsubscribe settings
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#223
  def update_domain_tracking_unsubscribe_settings(domain, options = T.unsafe(nil)); end

  # Public: Update the CNAME used for tracking opens and clicks
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # options - [Hash] of
  #   web_prefix  - [String] change the tracking CNAME for a domain.
  #
  # Returns [Hash] with message key
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#263
  def update_domain_web_prefix(domain, options = T.unsafe(nil)); end

  # Public: Updates the specified SMTP credentials.
  #
  # domain  - [String] Name of the domain (ex. domain.com)
  # login  - [String] The user name (ex. bob.bar)
  # options - [Hash] of
  #   password  - [String] A password for the SMTP credentials. (Length Min 5, Max 32)
  #
  # Returns [Hash] with message key
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#130
  def update_smtp_credentials(domain, login, options = T.unsafe(nil)); end

  # Public: Verify domain, update domain records
  #   Unknown status - this is not in the current Mailgun API
  #   Do no rely on this being available in future releases.
  #
  # domain - [String] Domain name
  #
  # Returns [Hash] Information on the updated/verified domains
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#47
  def verify(domain); end

  # Public: Verify domain, update domain records
  #   Unknown status - this is not in the current Mailgun API
  #   Do no rely on this being available in future releases.
  #
  # domain - [String] Domain name
  #
  # Returns [Hash] Information on the updated/verified domains
  #
  # source://mailgun-ruby//lib/mailgun/domains/domains.rb#52
  def verify_domain(domain); end
end

# Public: A basic class for mananging errors.
# Inherits from StandardError (previously RuntimeError) as not all errors are
# runtime errors.
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#6
class Mailgun::Error < ::StandardError
  # Public: initialize a Mailgun:Error object
  #
  # message - a String describing the error
  # object  - an object with details about the error
  #
  # @return [Error] a new instance of Error
  #
  # source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#15
  def initialize(message = T.unsafe(nil), object = T.unsafe(nil)); end

  # Public: get an object an error is instantiated with
  #
  # source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#9
  def object; end
end

# A Mailgun::Events object makes it really simple to consume
#   Mailgun's events from the Events endpoint.
#
# This is not yet comprehensive.
#
# Examples
#
#    See the Github documentation for full examples.
#
# source://mailgun-ruby//lib/mailgun/events/events.rb#13
class Mailgun::Events
  include ::Enumerable

  # Public: event initializer
  #
  # client - an instance of Mailgun::Client
  # domain - the domain to build queries
  #
  # @return [Events] a new instance of Events
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#20
  def initialize(client, domain); end

  # Public: Allows iterating through all events and performs automatic paging.
  #
  # &block - Block to execute on items.
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#61
  def each(&block); end

  # Public: Issues a simple get against the client. Alias of `next`.
  #
  # params - a Hash of query options and/or filters.
  #
  # Returns a Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#32
  def get(params = T.unsafe(nil)); end

  # Public: Using built in paging, obtains the next set of data.
  # If an events request hasn't been sent previously, this will send one
  #   without parameters
  #
  # params - a Hash of query options and/or filters.
  #
  # Returns a Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#43
  def next(params = T.unsafe(nil)); end

  # Public: Using built in paging, obtains the previous set of data.
  # If an events request hasn't been sent previously, this will send one
  #   without parameters
  #
  # params - a Hash of query options and/or filters.
  #
  # Returns Mailgun::Response object.
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#54
  def previous(params = T.unsafe(nil)); end

  private

  # Internal: construct the event path to be used by the client
  #
  # paging - the URL key for previous/next set of results
  #
  # Returns a String of the partial URI
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#114
  def construct_url(paging = T.unsafe(nil)); end

  # Internal: given a paging URL, extract the endpoint
  #
  # response - the endpoint for the previous/next page
  #
  # Returns a String of the partial URI if the given url follows the regular API format
  # Returns nil in other cases (e.g. when given nil, or an irrelevant url)
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#103
  def extract_endpoint_from(url = T.unsafe(nil)); end

  # Internal: given an event response, pull and store the paging keys
  #
  # response - a Mailgun::Response object
  #
  # Return is irrelevant.
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#89
  def extract_paging(response); end

  # Internal: Makes and processes the event request through the client
  #
  # params - optional Hash of query options
  # paging - the URL key used for previous/next requests
  #
  # Returns a Mailgun.Response object.
  #
  # source://mailgun-ruby//lib/mailgun/events/events.rb#78
  def get_events(params = T.unsafe(nil), paging = T.unsafe(nil)); end
end

# A Mailgun::MessageBuilder object is used to create a valid payload
# for the Mailgun API messages endpoint. If you prefer step by step message
# generation through your code, this class is for you.
#
# See the Github documentation for full examples.
#
# source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#12
class Mailgun::MessageBuilder
  # Public: Creates a new MessageBuilder object.
  #
  # @return [MessageBuilder] a new instance of MessageBuilder
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#17
  def initialize; end

  # Adds a series of attachments, when called upon.
  #
  # @param attachment [String|File] A file object for attaching as an attachment.
  # @param filename [String] The filename you wish the attachment to be.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#133
  def add_attachment(attachment, filename = T.unsafe(nil)); end

  # Add campaign IDs to message. Limit of 3 per message.
  #
  # @param campaign_id [String] A defined campaign ID to add to the message.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#186
  def add_campaign_id(campaign_id); end

  # Add custom parameter to the message. A custom parameter is any parameter that
  # is not yet supported by the SDK, but available at the API. Note: No validation
  # is performed. Don't forget to prefix the parameter with o, h, or v.
  #
  # @param name [string] A name for the custom parameter.
  # @param data [string] A string of data for the parameter.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#301
  def add_custom_parameter(name, data); end

  # Adds an inline image to the message object.
  #
  # @param inline_image [String|File] A file object for attaching an inline image.
  # @param filename [String] The filename you wish the inline image to be.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#142
  def add_inline_image(inline_image, filename = T.unsafe(nil)); end

  # Adds a specific type of recipient to the message object.
  #
  # WARNING: Setting 'h:reply-to' with add_recipient() is deprecated! Use 'reply_to' instead.
  #
  # @param recipient_type [String] The type of recipient. "to", "cc", "bcc" or "h:reply-to".
  # @param address [String] The email address of the recipient to add to the message object.
  # @param variables [Hash] A hash of the variables associated with the recipient. We recommend "first" and "last" at a minimum!
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#34
  def add_recipient(recipient_type, address, variables = T.unsafe(nil)); end

  # Add tags to message. Limit of 10 per message.
  #
  # @param tag [String] A defined campaign ID to add to the message.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#197
  def add_tag(tag); end

  # Set an AMP part for the message object
  #
  # @param amp [String] The AMP HTML for the email.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#124
  def amp_html(amp = T.unsafe(nil)); end

  # Set a html body for the message object
  #
  # @param html_body [String] The html body for the email.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#110
  def body_html(html_body = T.unsafe(nil)); end

  # Set a text body for the message object
  #
  # @param text_body [String] The text body for the email.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#96
  def body_text(text_body = T.unsafe(nil)); end

  # Returns the value of attribute counters.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#14
  def counters; end

  # Enable Delivery delay on message. Specify an RFC2822 date, and Mailgun
  # will not deliver the message until that date/time. For conversion
  # options, see Ruby "Time". Example: "October 25, 2013 10:00PM CST" will
  # be converted to "Fri, 25 Oct 2013 22:00:00 -0600".
  #
  # @param timestamp [String] A date and time, including a timezone.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#244
  def deliver_at(timestamp); end

  # Turn DKIM on or off per message
  #
  # @param mode [Boolean] The boolean or string value(will fix itself)
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#172
  def dkim(mode); end

  # Sets the from address for the message
  #
  # @param address [String] The address of the sender.
  # @param variables [Hash] A hash of the variables associated with the recipient. We recommend "first" and "last" at a minimum!
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#55
  def from(address, vars = T.unsafe(nil)); end

  # Add custom data to the message. The data should be either a hash or JSON
  # encoded. The custom data will be added as a header to your message.
  #
  # @param name [string] A name for the custom data. (Ex. X-Mailgun-<Name of Data>: {})
  # @param data [Hash] Either a hash or JSON string.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#261
  def header(name, data); end

  # Adds a List-Unsubscribe for the message header.
  #
  # @param *variables [Array<String>] Any number of url or mailto
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#150
  def list_unsubscribe(*variables); end

  # Returns the value of attribute message.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#14
  def message; end

  # Set the Message-Id header to a custom value. Don't forget to enclose the
  # Message-Id in angle brackets, and ensure the @domain is present. Doesn't
  # use simple or complex setters because it should not set value in an array.
  #
  # @param data [string] A string of data for the parameter. Passing nil or
  #   empty string will delete h:Message-Id key and value from @message hash.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#312
  def message_id(data = T.unsafe(nil)); end

  # Set the message's Reply-To address.
  #
  # Rationale: According to RFC, only one Reply-To address is allowed, so it
  # is *okay* to bypass the set_multi_simple and set reply-to directly.
  #
  # @param address [String] The email address to provide as Reply-To.
  # @param variables [Hash] A hash of variables associated with the recipient.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#73
  def reply_to(address, variables = T.unsafe(nil)); end

  # Depreciated: 'set_click_tracking. is deprecated. Please use 'track_clicks' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#232
  def set_click_tracking(tracking); end

  # Deprecated: 'set_custom_data' is deprecated. Please use 'header' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#272
  def set_custom_data(name, data); end

  # Deprecated: 'set_delivery_time' is deprecated. Please use 'deliver_at' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#250
  def set_delivery_time(timestamp); end

  # Deprecated: 'set_dkim' is deprecated. Please use 'dkim' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#177
  def set_dkim(mode); end

  # Deprecated: please use 'from' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#60
  def set_from_address(address, variables = T.unsafe(nil)); end

  # Deprecated: Please use "body_html" instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#115
  def set_html_body(html_body = T.unsafe(nil)); end

  # Deprecated: 'set_message_id' is deprecated. Use 'message_id' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#319
  def set_message_id(data = T.unsafe(nil)); end

  # Deprecated: 'set_open_tracking' is deprecated. Please use 'track_opens' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#216
  def set_open_tracking(tracking); end

  # Deprecated: Please use "subject" instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#87
  def set_subject(subj = T.unsafe(nil)); end

  # Deprecated: 'set_test_mode' is depreciated. Please use 'test_mode' instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#163
  def set_test_mode(mode); end

  # Deprecated: Please use "body_text" instead.
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#101
  def set_text_body(text_body = T.unsafe(nil)); end

  # Set a subject for the message object
  #
  # @param subject [String] The subject for the email.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#82
  def subject(subj = T.unsafe(nil)); end

  # Set name of a template stored via template API. See Templates for more information
  # https://documentation.mailgun.com/en/latest/api-templates.html
  #
  # @param tag [String] A defined template name to use. Passing nil or
  #   empty string will delete template key and value from @message hash.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#330
  def template(template_name = T.unsafe(nil)); end

  # Turn off or on template rendering in the text part
  # of the message in case of template sending.
  #
  # @param tracking [Boolean] Boolean true or false.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#352
  def template_text(mode); end

  # Set specific template version.
  #
  # @param tag [String] A defined template name to use. Passing nil or
  #   empty string will delete template key and value from @message hash.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#341
  def template_version(version = T.unsafe(nil)); end

  # Send a message in test mode. (The message won't really be sent to the recipient)
  #
  # @param mode [Boolean] The boolean or string value (will fix itself)
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#158
  def test_mode(mode); end

  # Turn Click Tracking on and off, on a per message basis.
  #
  # @param mode [String] True, False, or HTML (for HTML only tracking)
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#225
  def track_clicks(mode); end

  # Turn Open Tracking on and off, on a per message basis.
  #
  # @param tracking [Boolean] Boolean true or false.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#209
  def track_opens(mode); end

  # Attaches custom JSON data to the message. See the following doc page for more info.
  # https://documentation.mailgun.com/user_manual.html#attaching-data-to-messages
  #
  # @param name [String] A name for the custom variable block.
  # @param data [String|Hash] Either a string or a hash. If it is not valid JSON or
  #   can not be converted to JSON, ParameterError will be raised.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#284
  def variable(name, data); end

  private

  # Adds multipart attachment using Faraday::Multipart::FilePart
  #
  # @param parameter [String] The message object parameter name.
  # @param value [String] The attachment.
  # @param filename [String] Filename of the attachment.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#394
  def add_faraday_attachment(parameter, attachment, filename); end

  # Private: Adds a file to the message.
  #
  # Returns nothing
  #
  # @param disposition [Symbol] The type of file: :attachment or :inline
  # @param attachment [String|File] A file object for attaching as an attachment.
  # @param filename [String] The filename you wish the attachment to be.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#466
  def add_file(disposition, filedata, filename); end

  # Converts boolean type to string
  #
  # @param value [String] The item to convert
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#403
  def bool_lookup(value); end

  # Private: given an object attempt to make it into JSON
  #
  # obj - an object. Hopefully a JSON string or Hash
  #
  # Returns a JSON object or raises ParameterError
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#426
  def make_json(obj); end

  # Parses the address and gracefully handles any
  # missing parameters. The result should be something like:
  # "'First Last' <person@domain.com>"
  #
  # @param address [String] The email address to parse.
  # @param variables [Hash] A list of recipient variables.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#441
  def parse_address(address, vars); end

  # Sets values within the multidict, however, allows
  # duplicate values for keys.
  #
  # @param parameter [String] The message object parameter name.
  # @param value [String] The value of the parameter.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#384
  def set_multi_complex(parameter, value); end

  # Sets values within the multidict, however, prevents
  # duplicate values for keys.
  #
  # @param parameter [String] The message object parameter name.
  # @param value [String] The value of the parameter.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#374
  def set_multi_simple(parameter, value); end

  # Sets a single value in the message hash where "multidict" features are not needed.
  # Does *not* permit duplicate params.
  #
  # @param parameter [String] The message object parameter name.
  # @param value [String] The value of the parameter.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#364
  def set_single(parameter, value); end

  # Validates whether the input is JSON.
  #
  # @param json_ [String] The suspected JSON string.
  # @return [void]
  #
  # source://mailgun-ruby//lib/mailgun/messages/message_builder.rb#414
  def valid_json?(json_); end
end

# A Mailgun::Metrics object is a simple interface to Mailgun Metrics.
# Uses Mailgun
#
# source://mailgun-ruby//lib/mailgun/metrics/metrics.rb#6
class Mailgun::Metrics
  # Public: creates a new Mailgun::Metrics instance.
  # Defaults to Mailgun::Client
  #
  # @return [Metrics] a new instance of Metrics
  #
  # source://mailgun-ruby//lib/mailgun/metrics/metrics.rb#9
  def initialize(client = T.unsafe(nil)); end

  # Public: Post query to get account metrics
  #
  # options - [Hash] of
  #     start - [String] A start date (default: 7 days before current time). Must be in RFC 2822 format.
  #     end - [String] An end date (default: current time). Must be in RFC 2822 format.
  #     resolution - [String] A resolution in the format of 'day' 'hour' 'month'. Default is day.
  #     duration - [String] A duration in the format of '1d' '2h' '2m'. If duration is provided then it is calculated from the end date and overwrites the start date.
  #     dimensions - [Array] Attributes of the metric data such as 'subaccount'.
  #     metrics - [Array] Name of the metrics to receive the stats for such as 'processed_count'
  #     filter - [Object]
  #         AND: - [Array] of objects
  #             attribute - [String]
  #             comparator - [String]
  #             values - [Array] of objects
  #                 label - [String]
  #                 value - [String]
  #     include_subaccounts - [Boolean] Include stats from all subaccounts.
  #     include_aggregates - [Boolean] Include top-level aggregate metrics.
  #
  # Returns [Hash] Metrics
  #
  # source://mailgun-ruby//lib/mailgun/metrics/metrics.rb#33
  def account_metrics(options = T.unsafe(nil)); end

  # Public: Post query to get account usage metrics
  #
  # options - [Hash] of
  #     start - [String] A start date (default: 7 days before current time). Must be in RFC 2822 format.
  #     end - [String] An end date (default: current time). Must be in RFC 2822 format.
  #     resolution - [String] A resolution in the format of 'day' 'hour' 'month'. Default is day.
  #     duration - [String] A duration in the format of '1d' '2h' '2m'. If duration is provided then it is calculated from the end date and overwrites the start date.
  #     dimensions - [Array] Attributes of the metric data such as 'subaccount'.
  #     metrics - [Array] Name of the metrics to receive the stats for such as 'processed_count'
  #     filter - [Object]
  #         AND: - [Array] of objects
  #             attribute - [String]
  #             comparator - [String]
  #             values - [Array] of objects
  #                 label - [String]
  #                 value - [String]
  #     include_subaccounts - [Boolean] Include stats from all subaccounts.
  #     include_aggregates - [Boolean] Include top-level aggregate metrics.
  #
  # Returns [Hash] Metrics
  #
  # source://mailgun-ruby//lib/mailgun/metrics/metrics.rb#57
  def account_usage_metrics(options = T.unsafe(nil)); end
end

# Public: Provides methods for creating and handling opt-in URLs,
#   particularlly for mailing lists.
#
# See: https://github.com/mailgun/mailgun-ruby/blob/master/OptInHandler.md
#
# source://mailgun-ruby//lib/mailgun/lists/opt_in_handler.rb#11
class Mailgun::OptInHandler
  class << self
    # Generates a hash that can be used to validate opt-in recipients. Encodes
    # all the necessary data in the URL.
    #
    # @param mailing_list [String] The mailing list the user should be subscribed to.
    # @param secret_app_id [String] A secret passphrase used as a constant for the hash.
    # @param recipient_address [Hash] The address of the user that should be subscribed.
    # @return [String] A url encoded URL suffix hash.
    #
    # source://mailgun-ruby//lib/mailgun/lists/opt_in_handler.rb#20
    def generate_hash(mailing_list, secret_app_id, recipient_address); end

    # Validates the hash provided from the generate_hash method.
    #
    # @param secret_app_id [String] A secret passphrase used as a constant for the hash.
    # @param unique_hash [Hash] The hash from the user. Likely via link click.
    # @return [Hash or Boolean] A hash with 'recipient_address' and 'mailing_list', if validates. Otherwise, boolean false.
    #
    # source://mailgun-ruby//lib/mailgun/lists/opt_in_handler.rb#40
    def validate_hash(secret_app_id, unique_hash); end
  end
end

# Public: Class for managing parameter errors, with a pretty name.
# Inherits from Mailgun::Error
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#23
class Mailgun::ParameterError < ::Mailgun::Error; end

# Public: Class for managing parsing errors, with a pretty name.
# Inherits from Mailgun::Error
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#27
class Mailgun::ParseError < ::Mailgun::Error; end

# A Mailgun::Response object is instantiated for each response generated
# by the Client request. The Response object supports deserialization of
# the JSON result. Or, if you prefer JSON or YAML formatting, call the
# method for conversion.
#
# See the Github documentation for full examples.
#
# source://mailgun-ruby//lib/mailgun/response.rb#8
class Mailgun::Response
  # @return [Response] a new instance of Response
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#19
  def initialize(response); end

  # All responses have a payload and a status corresponding to http, though
  #   slightly different
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#11
  def body; end

  # All responses have a payload and a status corresponding to http, though
  #   slightly different
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#11
  def body=(_arg0); end

  # All responses have a payload and a status corresponding to http, though
  #   slightly different
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#11
  def code; end

  # All responses have a payload and a status corresponding to http, though
  #   slightly different
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#11
  def code=(_arg0); end

  # All responses have a payload and a status corresponding to http, though
  #   slightly different
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#11
  def status; end

  # All responses have a payload and a status corresponding to http, though
  #   slightly different
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#11
  def status=(_arg0); end

  # Returns true if response status is 2xx
  #
  # @return [Boolean] A boolean that binarizes the response status result.
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#65
  def success?; end

  # Return response as Ruby Hash
  #
  # @return [Hash] A standard Ruby Hash containing the HTTP result.
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#29
  def to_h; end

  # Replace @body with Ruby Hash
  #
  # @return [Hash] A standard Ruby Hash containing the HTTP result.
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#38
  def to_h!; end

  # Return response as Yaml
  #
  # @return [String] A string containing response as YAML
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#47
  def to_yaml; end

  # Replace @body with YAML
  #
  # @return [String] A string containing response as YAML
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#56
  def to_yaml!; end

  class << self
    # source://mailgun-ruby//lib/mailgun/response.rb#14
    def from_hash(h); end
  end
end

# source://mailgun-ruby//lib/mailgun/response.rb#13
class Mailgun::Response::ResponseHash < ::Struct
  # Returns the value of attribute body
  #
  # @return [Object] the current value of body
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#13
  def body; end

  # Sets the attribute body
  #
  # @param value [Object] the value to set the attribute body to.
  # @return [Object] the newly set value
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#13
  def body=(_); end

  # Returns the value of attribute status
  #
  # @return [Object] the current value of status
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#13
  def status; end

  # Sets the attribute status
  #
  # @param value [Object] the value to set the attribute status to.
  # @return [Object] the newly set value
  #
  # source://mailgun-ruby//lib/mailgun/response.rb#13
  def status=(_); end

  class << self
    # source://mailgun-ruby//lib/mailgun/response.rb#13
    def [](*_arg0); end

    # source://mailgun-ruby//lib/mailgun/response.rb#13
    def inspect; end

    # source://mailgun-ruby//lib/mailgun/response.rb#13
    def keyword_init?; end

    # source://mailgun-ruby//lib/mailgun/response.rb#13
    def members; end

    # source://mailgun-ruby//lib/mailgun/response.rb#13
    def new(*_arg0); end
  end
end

# A Mailgun::Subaccounts object is a simple CRUD interface to Mailgun Subaccounts.
# Uses Mailgun
#
# source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#7
class Mailgun::Subaccounts
  # Public: creates a new Mailgun::Subaccounts instance.
  # Defaults to Mailgun::Client
  #
  # @return [Subaccounts] a new instance of Subaccounts
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#12
  def initialize(client = T.unsafe(nil)); end

  # Returns the value of attribute client.
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#8
  def client; end

  # Public: Add Subaccount
  #
  # name  - [String] Name of the subaccount being created
  # options - [Hash] of
  #     name - [String] Name of the subaccount being created.
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the subaccount.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] of created subaccount
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#53
  def create(name, options = T.unsafe(nil)); end

  # Public: Disable a subaccount
  #
  # subaccount_id - [String] subaccount name to disable
  # options - [Hash] of
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the subaccount.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] Information on the requested subaccount.
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#66
  def disable(subaccount_id, options = T.unsafe(nil)); end

  # Public: Enable a subaccount
  #
  # subaccount_id - [String] subaccount name to enable
  # options - [Hash] of
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the subaccount.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] Information on the requested subaccount.
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#79
  def enable(subaccount_id, options = T.unsafe(nil)); end

  # Public: Get subaccounts
  # options - [Hash] of
  #     limit  - [Integer] Maximum number of records to return. (10 by default)
  #     skip     [Integer] Number of records to skip
  #     sort     [Array] “asc” or “desc”
  #     enabled  [boolean] (Optional) Returns all enabled/disabled subaccounts, defaults to all if omitted
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the subaccount.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Array] A list of subaccounts (hash)
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#29
  def get_subaccounts(options = T.unsafe(nil)); end

  # Public: Get subaccount information
  #
  # subaccount_id - [String] subaccount name to lookup for
  # options - [Hash] of
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the subaccount.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] Information on the requested subaccount.
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#39
  def info(subaccount_id, options = T.unsafe(nil)); end

  # Public: Get subaccounts
  # options - [Hash] of
  #     limit  - [Integer] Maximum number of records to return. (10 by default)
  #     skip     [Integer] Number of records to skip
  #     sort     [Array] “asc” or “desc”
  #     enabled  [boolean] (Optional) Returns all enabled/disabled subaccounts, defaults to all if omitted
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the subaccount.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Array] A list of subaccounts (hash)
  #
  # source://mailgun-ruby//lib/mailgun/subaccounts/subaccounts.rb#26
  def list(options = T.unsafe(nil)); end
end

# The Mailgun::Suppressions object makes it easy to manage "suppressions"
# attached to an account. "Suppressions" means bounces, unsubscribes, and complaints.
#
# source://mailgun-ruby//lib/mailgun/suppressions.rb#9
class Mailgun::Suppressions
  # @param client [Mailgun::Client] API client to use for requests
  # @param domain [String] Domain name to use for the suppression endpoints.
  # @return [Suppressions] a new instance of Suppressions
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#13
  def initialize(client, domain); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#51
  def create_bounce(params = T.unsafe(nil)); end

  # Creates multiple bounces on the Mailgun API.
  # If a bounce does not have a valid structure, it will be added to a list of unsendable bounces.
  # The list of unsendable bounces will be returned at the end of this operation.
  #
  # If more than 999 bounce entries are provided, the list will be split and recursive calls will be made.
  #
  # @param data [Array] Array of bounce hashes
  # @return [Response] Mailgun API response
  # @return [Array] Return values from recursive call for list split.
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#64
  def create_bounces(data); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#193
  def create_complaint(params = T.unsafe(nil)); end

  # Creates multiple complaints on the Mailgun API.
  # If a complaint does not have a valid structure, it will be added to a list of unsendable complaints.
  # The list of unsendable complaints will be returned at the end of this operation.
  #
  # If more than 999 complaint entries are provided, the list will be split and recursive calls will be made.
  #
  # @param data [Array] Array of complaint hashes
  # @return [Response] Mailgun API response
  # @return [Array] Return values from recursive call for list split.
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#206
  def create_complaints(data); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#124
  def create_unsubscribe(params = T.unsafe(nil)); end

  # Creates multiple unsubscribes on the Mailgun API.
  # If an unsubscribe does not have a valid structure, it will be added to a list of unsendable unsubscribes.
  # The list of unsendable unsubscribes will be returned at the end of this operation.
  #
  # If more than 999 unsubscribe entries are provided, the list will be split and recursive calls will be made.
  #
  # @param data [Array] Array of unsubscribe hashes
  # @return [Response] Mailgun API response
  # @return [Array] Return values from recursive call for list split.
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#137
  def create_unsubscribes(data); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#106
  def delete_all_bounces; end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#102
  def delete_bounce(address); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#241
  def delete_complaint(address); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#175
  def delete_unsubscribe(address, params = T.unsafe(nil)); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#47
  def get_bounce(address); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#189
  def get_complaint(address); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#120
  def get_unsubscribe(address); end

  # Bounces Endpoint (/v3/:domain/bounces)
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#41
  def list_bounces(params = T.unsafe(nil)); end

  # Complaints Endpoint (/v3/:domain/complaints)
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#183
  def list_complaints(params = T.unsafe(nil)); end

  # Unsubscribes Endpoint (/v3/:domain/unsubscribes)
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#114
  def list_unsubscribes(params = T.unsafe(nil)); end

  # Paging operations
  #
  # source://mailgun-ruby//lib/mailgun/suppressions.rb#25
  def next; end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#31
  def prev; end

  private

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#247
  def escape_address(address); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#255
  def extract_paging(response); end

  # source://mailgun-ruby//lib/mailgun/suppressions.rb#251
  def get_from_paging(uri, params = T.unsafe(nil)); end
end

# A Mailgun::Tags object is a simple CRUD interface to Mailgun Tags.
# Uses Mailgun
#
# source://mailgun-ruby//lib/mailgun/tags/tags.rb#7
class Mailgun::Tags
  # Public: creates a new Mailgun::Tags instance.
  # Defaults to Mailgun::Client
  #
  # @return [Tags] a new instance of Tags
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#11
  def initialize(client = T.unsafe(nil)); end

  # Public: Get a list of countries of origin for a given domain for different event types.
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  #
  # Returns [Hash] of countries of origin for a given domain
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#90
  def get_countries_aggregated_stats(domain, tag); end

  # Public: Get a list of devices for a given domain that have triggered event types.
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  #
  # Returns [Hash] of devices for a given domain
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#114
  def get_devices_aggregated_stats(domain, tag); end

  # Public: Get a list of email providers for a given domain for different event types
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  #
  # Returns [Hash] of email providers for a given domain
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#102
  def get_providers_aggregated_stats(domain, tag); end

  # Public: Get tag information
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  #
  # Returns [Hash] Information on the requested tag.
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#33
  def get_tag(domain, tag); end

  # Public: Get statistics for a given tag
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  # options - [Hash] of
  #     event - [String] The type of the event. Required. (ex. accepted, delivered, failed, opened)
  #     start - [String] The starting time. Should be in RFC 282 or unix epoch format. Default: 7 days from the current time.
  #     end   - [String] The ending date. Should be in RFC 2822 or unix epoch time in seconds. Default: current time.
  #     resolution   - [String] Can be either hour, day or month. Default: day
  #     duration   - [String] Period of time with resolution encoded. If provided, overwrites the start date and resolution.
  #
  # Returns [Hash] of tag stats info
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#65
  def get_tag_stats(domain, tag, options = T.unsafe(nil)); end

  # Public: Get Tags
  #
  # domain - [String] Domain name where tag is stored
  # options - [Hash] of
  #    limit  - [Integer] Number of entries to return. Default: 100.
  #
  # Returns [Array] A list of tags (hash)
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#22
  def get_tags(domain, options = T.unsafe(nil)); end

  # Public: Delete Tag
  # NOTE: Deletes the tag. Note: The statistics for the tag are not destroyed.
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#78
  def remove(domain, tag); end

  # Public: Updates a given tag with the information provided
  #
  # domain - [String] Domain name where tag is stored
  # tag    - [String] Tag name to lookup for
  # options - [Hash] of
  #     description - [String] Updated description of the tag
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/tags/tags.rb#47
  def update(domain, tag, options = T.unsafe(nil)); end
end

# A Mailgun::Templates object is a simple CRUD interface to Mailgun Templates.
# Uses Mailgun
#
# source://mailgun-ruby//lib/mailgun/templates/templates.rb#7
class Mailgun::Templates
  # Public: creates a new Mailgun::Templates instance.
  # Defaults to Mailgun::Client
  #
  # @return [Templates] a new instance of Templates
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#11
  def initialize(client = T.unsafe(nil)); end

  # Public: Add template
  #
  # domain  - [String] Name of the domain for new template(ex. domain.com)
  # options - [Hash] of
  #     name - [String] Name of the template being stored.
  #     description   - [String] Description of the template being stored
  #     template      - [String] (Optional) Content of the template
  #     tag           - [String] (Optional) Initial tag of the created version.
  #     comment       - [String] (Optional) Version comment.
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the template.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] of created template
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#28
  def create(domain, options = T.unsafe(nil)); end

  # Public: Create a new version of a template
  #
  # domain        - [String] Name of the domain for new template(ex. domain.com)
  # template_name - [String] Template name to lookup for
  # options - [Hash] of
  #     template      - [String] Content of the template
  #     tag           - [String] Initial tag of the created version.
  #     comment       - [String] (Optional) Version comment.
  #     active        - [Boolean] (Optional) If this flag is set to yes, this version becomes active
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the template.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] of updated template
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#116
  def create_version(domain, template_name, options = T.unsafe(nil)); end

  # Public: Delete Template
  # NOTE: This method deletes all versions of the specified template.
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#74
  def delete(domain, template_name); end

  # Public: Delete Template
  # NOTE: This method deletes all versions of the specified template.
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#75
  def delete_template(domain, template_name); end

  # Public: Delete Templates
  # NOTE: This method deletes all stored templates for the domain.
  #
  # domain        - [String] Domain name where template is stored
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#101
  def delete_templates(domain); end

  # Public: Delete the version of the template
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  # tag           - [String] Version tag to lookup for
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#163
  def delete_version(domain, template_name, tag); end

  # Public: Get Templates
  #
  # domain - [String] Domain name where template is stored
  # page   - [String] Name of a page to retrieve. first, last, next, prev
  # limit  - [Integer] Maximum number of records to return. (100 by default)
  # p      - [Integer] Pivot is used to retrieve records in chronological order
  #
  # Returns [Array] A list of templates (hash)
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#89
  def get_templates(domain, options = T.unsafe(nil)); end

  # Public: Get template information
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  # options - [Hash] of
  #     active - [Boolean] (Optional) If this flag is set to yes the active version
  #               of the template is included in the response.
  #
  # Returns [Hash] Information on the requested template.
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#42
  def info(domain, template_name, options = T.unsafe(nil)); end

  # Public: Get template version information
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  # tag           - [String] Version tag to lookup for
  #
  # Returns [Hash] Information on the requested template + version.
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#129
  def info_version(domain, template_name, tag); end

  # Public: Get Templates
  #
  # domain - [String] Domain name where template is stored
  # page   - [String] Name of a page to retrieve. first, last, next, prev
  # limit  - [Integer] Maximum number of records to return. (100 by default)
  # p      - [Integer] Pivot is used to retrieve records in chronological order
  #
  # Returns [Array] A list of templates (hash)
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#85
  def list(domain, options = T.unsafe(nil)); end

  # Public: Delete Template
  # NOTE: This method deletes all versions of the specified template.
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#69
  def remove(domain, template_name); end

  # Public: Delete Templates
  # NOTE: This method deletes all stored templates for the domain.
  #
  # domain        - [String] Domain name where template is stored
  #
  # Returns [Boolean] if successful or not
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#97
  def remove_all(domain); end

  # Public: Get Template's Versions list
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  # options - [Hash] of
  # page   - [String] Name of a page to retrieve. first, last, next, prev
  # limit  - [Integer] Maximum number of records to return. (100 by default)
  # p      - [Integer] Pivot is used to retrieve records in chronological order
  #
  # Returns [Array] A list of template's versions (hash)
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#181
  def template_versions_list(domain, template_name, options = T.unsafe(nil)); end

  # Public: Update the metadata information of the template
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  # options - [Hash] of
  #     description - [String] Updated description of the template
  #
  # Returns [Hash] of updated domain
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#56
  def update(domain, template_name, options = T.unsafe(nil)); end

  # Public: Update the version of the template
  #
  # domain        - [String] Domain name where template is stored
  # template_name - [String] Template name to lookup for
  # tag           - [String] Version tag to lookup for
  # options - [Hash] of
  #     template      - [String] Content of the template
  #     comment       - [String] (Optional) Version comment.
  #     active        - [Boolean] (Optional) If this flag is set to yes, this version becomes active
  #     headers       - [String] (Optional) Key Value json dictionary of headers to be stored with the template.
  #                     ex.('{"Subject": "{{subject}}"}')
  #
  # Returns [Hash] of updated template's version
  #
  # source://mailgun-ruby//lib/mailgun/templates/templates.rb#149
  def update_version(domain, template_name, tag, options = T.unsafe(nil)); end
end

# Public: Class for managing unauthorized 401 errors
# Inherits from Mailgun::CommunicationError
#
# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#75
class Mailgun::Unauthorized < ::Mailgun::CommunicationError
  # @return [Unauthorized] a new instance of Unauthorized
  #
  # source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#78
  def initialize(error_message, response); end
end

# source://mailgun-ruby//lib/mailgun/exceptions/exceptions.rb#76
Mailgun::Unauthorized::CODE = T.let(T.unsafe(nil), Integer)

# source://mailgun-ruby//lib/mailgun/version.rb#3
Mailgun::VERSION = T.let(T.unsafe(nil), String)

# A Mailgun::Webhooks object is a simple CRUD interface to Mailgun Webhooks.
# Uses Mailgun
#
# source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#5
class Mailgun::Webhooks
  # Public creates a new Mailgun::Webhooks instance.
  #   Defaults to Mailgun::Client
  #
  # @return [Webhooks] a new instance of Webhooks
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#10
  def initialize(client = T.unsafe(nil)); end

  # Public: Add webhook
  #
  # domain - A String of the domain name (ex. domain.com)
  # action - A String of the action to create a webhook for
  # url    - A String of the url of the webhook
  #
  # Returns a Boolean of whether the webhook was created
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#52
  def add(domain, action, url = T.unsafe(nil)); end

  # Public: Sets all webhooks to the same URL
  #
  # domain - A String of the domain name
  # url    - A String of the url to set all webhooks to
  #
  # Returns true or false
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#69
  def add_all_webhooks(domain, url = T.unsafe(nil)); end

  # Public: Add webhook
  #
  # domain - A String of the domain name (ex. domain.com)
  # action - A String of the action to create a webhook for
  # url    - A String of the url of the webhook
  #
  # Returns a Boolean of whether the webhook was created
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#53
  def add_webhook(domain, action, url = T.unsafe(nil)); end

  # Public: Add webhook
  #
  # domain - A String of the domain name (ex. domain.com)
  # action - A String of the action to create a webhook for
  # url    - A String of the url of the webhook
  #
  # Returns a Boolean of whether the webhook was created
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#48
  def create(domain, action, url = T.unsafe(nil)); end

  # Public: Sets all webhooks to the same URL
  #
  # domain - A String of the domain name
  # url    - A String of the url to set all webhooks to
  #
  # Returns true or false
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#61
  def create_all(domain, url = T.unsafe(nil)); end

  # Public: Delete a specific webhook
  #
  # domain - The required String of domain name
  # action - The required String of the webhook action to delete
  #
  # Returns a Boolean of the success
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#99
  def delete(domain, action); end

  # Public: Delete all webhooks for a domain
  #
  # domain - A required String of the domain to remove all webhooks for
  #
  # Returns a Boolean on the success
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#113
  def delete_all(domain); end

  # Public: Delete all webhooks for a domain
  #
  # domain - A required String of the domain to remove all webhooks for
  #
  # Returns a Boolean on the success
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#114
  def delete_all_webooks(domain); end

  # Public: Delete a specific webhook
  #
  # domain - The required String of domain name
  # action - The required String of the webhook action to delete
  #
  # Returns a Boolean of the success
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#100
  def delete_webhook(domain, action); end

  # Public: Get webook information for a specific action
  #
  # domain - a String of Domain name to find a webhook url for
  # action - a String identifying the webhook to get the URL for
  #
  # Returns a String of the url for the identified webhook or an
  #   empty String if one is not set
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#39
  def get_webhook_url(domain, action); end

  # Public: Get Webhooks
  #
  # domain  - a string the domain name to retrieve webhooks for
  # options - a Hash of options
  #
  # Returns a Hash of the list of domains or nil
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#24
  def get_webhooks(domain, options = T.unsafe(nil)); end

  # Public: Get webook information for a specific action
  #
  # domain - a String of Domain name to find a webhook url for
  # action - a String identifying the webhook to get the URL for
  #
  # Returns a String of the url for the identified webhook or an
  #   empty String if one is not set
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#33
  def info(domain, action); end

  # Public: Get Webhooks
  #
  # domain  - a string the domain name to retrieve webhooks for
  # options - a Hash of options
  #
  # Returns a Hash of the list of domains or nil
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#20
  def list(domain, options = T.unsafe(nil)); end

  # Public: Delete a specific webhook
  #
  # domain - The required String of domain name
  # action - The required String of the webhook action to delete
  #
  # Returns a Boolean of the success
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#92
  def remove(domain, action); end

  # Public: Delete all webhooks for a domain
  #
  # domain - A required String of the domain to remove all webhooks for
  #
  # Returns a Boolean on the success
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#107
  def remove_all(domain); end

  # Public: Update webhook
  #
  # domain - A String of the domain name (ex. domain.com)
  # action - A String of the action to create a webhook for
  # url    - A String of the url of the webhook
  #
  # Returns a Boolean of whether the webhook was updated
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#78
  def update(domain, action, url = T.unsafe(nil)); end

  # Public: Update webhook
  #
  # domain - A String of the domain name (ex. domain.com)
  # action - A String of the action to create a webhook for
  # url    - A String of the url of the webhook
  #
  # Returns a Boolean of whether the webhook was updated
  #
  # source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#84
  def update_webhook(domain, action, url = T.unsafe(nil)); end
end

# source://mailgun-ruby//lib/mailgun/webhooks/webhooks.rb#6
Mailgun::Webhooks::ACTIONS = T.let(T.unsafe(nil), Array)

# source://mailgun-ruby//lib/railgun/errors.rb#1
module Railgun
  private

  # Acts on a Rails/ActionMailer message object and uses Mailgun::MessageBuilder
  # to construct a new message.
  #
  # @param mail [Mail::Message] message to transform
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#167
  def build_message_object(mail); end

  # Returns the decoded AMP HTML from the Mail::Message object if it is available,
  # otherwise nil.
  #
  # @param mail [Mail::Message] message to transform
  # @return [String]
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#242
  def extract_amp_html(mail); end

  # Returns the decoded HTML body from the Mail::Message object if available,
  # otherwise nil.
  #
  # @param mail [Mail::Message] message to transform
  # @return [String]
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#214
  def extract_body_html(mail); end

  # Returns the decoded text body from the Mail::Message object if it is available,
  # otherwise nil.
  #
  # @param mail [Mail::Message] message to transform
  # @return [String]
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#228
  def extract_body_text(mail); end

  # Returns the mail object from the Mail::Message object if AMP part exists,
  # (decomposing multipart into individual format if necessary)
  # otherwise nil.
  #
  # @param mail [Mail::Message] message to transform
  # @return [Mail::Message] mail message with its content-type = text/x-amp-html
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#281
  def retrieve_amp_part(mail); end

  # Returns the mail object from the Mail::Message object if html part exists,
  # (decomposing multipart into individual format if necessary)
  # otherwise nil.
  #
  # @param mail [Mail::Message] message to transform
  # @return [Mail::Message] mail message with its content-type = text/html
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#269
  def retrieve_html_part(mail); end

  # Returns the mail object from the Mail::Message object if text part exists,
  # (decomposing multipart into individual format if necessary)
  # otherwise nil.
  #
  # @param mail [Mail::Message] message to transform
  # @return [Mail::Message] mail message with its content-type = text/plain
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#257
  def retrieve_text_part(mail); end

  # Performs a series of transformations on the `mailgun*` attributes.
  # After prefixing them with the proper option type, they are added to
  # the message hash where they will then be sent to the API as JSON.
  #
  # It is important to note that headers set in `mailgun_headers` on the message
  # WILL overwrite headers set via `mail.headers()`.
  #
  # @param mail [Mail::Message] message to transform
  # @return [Hash] transformed message hash
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#94
  def transform_for_mailgun(mail); end

  class << self
    # Acts on a Rails/ActionMailer message object and uses Mailgun::MessageBuilder
    # to construct a new message.
    #
    # @param mail [Mail::Message] message to transform
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#167
    def build_message_object(mail); end

    # Returns the decoded AMP HTML from the Mail::Message object if it is available,
    # otherwise nil.
    #
    # @param mail [Mail::Message] message to transform
    # @return [String]
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#242
    def extract_amp_html(mail); end

    # Returns the decoded HTML body from the Mail::Message object if available,
    # otherwise nil.
    #
    # @param mail [Mail::Message] message to transform
    # @return [String]
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#214
    def extract_body_html(mail); end

    # Returns the decoded text body from the Mail::Message object if it is available,
    # otherwise nil.
    #
    # @param mail [Mail::Message] message to transform
    # @return [String]
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#228
    def extract_body_text(mail); end

    # Returns the mail object from the Mail::Message object if AMP part exists,
    # (decomposing multipart into individual format if necessary)
    # otherwise nil.
    #
    # @param mail [Mail::Message] message to transform
    # @return [Mail::Message] mail message with its content-type = text/x-amp-html
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#281
    def retrieve_amp_part(mail); end

    # Returns the mail object from the Mail::Message object if html part exists,
    # (decomposing multipart into individual format if necessary)
    # otherwise nil.
    #
    # @param mail [Mail::Message] message to transform
    # @return [Mail::Message] mail message with its content-type = text/html
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#269
    def retrieve_html_part(mail); end

    # Returns the mail object from the Mail::Message object if text part exists,
    # (decomposing multipart into individual format if necessary)
    # otherwise nil.
    #
    # @param mail [Mail::Message] message to transform
    # @return [Mail::Message] mail message with its content-type = text/plain
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#257
    def retrieve_text_part(mail); end

    # Performs a series of transformations on the `mailgun*` attributes.
    # After prefixing them with the proper option type, they are added to
    # the message hash where they will then be sent to the API as JSON.
    #
    # It is important to note that headers set in `mailgun_headers` on the message
    # WILL overwrite headers set via `mail.headers()`.
    #
    # @param mail [Mail::Message] message to transform
    # @return [Hash] transformed message hash
    #
    # source://mailgun-ruby//lib/railgun/mailer.rb#94
    def transform_for_mailgun(mail); end
  end
end

# source://mailgun-ruby//lib/railgun/attachment.rb#3
class Railgun::Attachment < ::StringIO
  # @return [Attachment] a new instance of Attachment
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#8
  def initialize(attachment, *args); end

  # source://mailgun-ruby//lib/railgun/attachment.rb#43
  def attach_to_message!(mb); end

  # Returns the value of attribute content_type.
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#5
  def content_type; end

  # Returns the value of attribute filename.
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#5
  def filename; end

  # @return [Boolean]
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#31
  def inline?; end

  # source://mailgun-ruby//lib/railgun/attachment.rb#35
  def is_original_filename; end

  # Returns the value of attribute original_filename.
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#5
  def original_filename; end

  # Returns the value of attribute overwritten_filename.
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#5
  def overwritten_filename; end

  # Returns the value of attribute path.
  #
  # source://mailgun-ruby//lib/railgun/attachment.rb#5
  def path; end

  # source://mailgun-ruby//lib/railgun/attachment.rb#39
  def source_filename; end
end

# source://mailgun-ruby//lib/railgun/errors.rb#14
class Railgun::ConfigurationError < ::Railgun::Error; end

# source://mailgun-ruby//lib/railgun/errors.rb#3
class Railgun::Error < ::StandardError
  # @return [Error] a new instance of Error
  #
  # source://mailgun-ruby//lib/railgun/errors.rb#7
  def initialize(message = T.unsafe(nil), object = T.unsafe(nil)); end

  # Returns the value of attribute object.
  #
  # source://mailgun-ruby//lib/railgun/errors.rb#5
  def object; end
end

# source://mailgun-ruby//lib/railgun/errors.rb#17
class Railgun::InternalError < ::Railgun::Error
  # @return [InternalError] a new instance of InternalError
  #
  # source://mailgun-ruby//lib/railgun/errors.rb#21
  def initialize(source_exc, message = T.unsafe(nil), object = T.unsafe(nil)); end

  # Returns the value of attribute source_exception.
  #
  # source://mailgun-ruby//lib/railgun/errors.rb#19
  def source_exception; end
end

# Railgun::Mailer is an ActionMailer provider for sending mail through
# Mailgun.
#
# source://mailgun-ruby//lib/railgun/mailer.rb#11
class Railgun::Mailer
  # Initialize the Railgun mailer.
  #
  # @param config [Hash] Hash of config values, typically from `app_config.action_mailer.mailgun_config`
  # @return [Mailer] a new instance of Mailer
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#23
  def initialize(config); end

  # [Hash] config ->
  #   Requires *at least* `api_key` and `domain` keys.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#18
  def config; end

  # [Hash] config ->
  #   Requires *at least* `api_key` and `domain` keys.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#18
  def config=(_arg0); end

  # source://mailgun-ruby//lib/railgun/mailer.rb#49
  def deliver!(mail); end

  # [Hash] config ->
  #   Requires *at least* `api_key` and `domain` keys.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#18
  def domain; end

  # [Hash] config ->
  #   Requires *at least* `api_key` and `domain` keys.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#18
  def domain=(_arg0); end

  # source://mailgun-ruby//lib/railgun/mailer.rb#68
  def mailgun_client; end

  # [Hash] config ->
  #   Requires *at least* `api_key` and `domain` keys.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#18
  def settings; end

  # [Hash] config ->
  #   Requires *at least* `api_key` and `domain` keys.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#18
  def settings=(_arg0); end

  private

  # Set @mg_domain from mail[:domain] header if present, then remove it to prevent being sent.
  #
  # source://mailgun-ruby//lib/railgun/mailer.rb#75
  def set_mg_domain(mail); end
end

# List of the headers that will be ignored when copying headers from `mail.header_fields`
#
# source://mailgun-ruby//lib/railgun/mailer.rb#14
Railgun::Mailer::IGNORED_HEADERS = T.let(T.unsafe(nil), Array)

# source://mailgun-ruby//lib/railgun/railtie.rb#4
class Railgun::Railtie < ::Rails::Railtie; end
