# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DailyMailer`.
# Please instead update this file by running `bin/tapioca dsl DailyMailer`.


class DailyMailer
  class << self
    sig { params(user: T.untyped, interval: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def daily_mail(user, interval: T.unsafe(nil)); end
  end
end
