default: &default
  adapter: postgresql

development:
  <<: *default
  database: ntsb-alerts_development

test:
  <<: *default
  database: ntsb-alerts_test

production:
  primary:
    <<: *default
    database: ntsb_alerts
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    database: ntsb_alerts
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: ntsb_alerts
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: ntsb_alerts
    migrations_paths: db/cable_migrate
