default: &default
  adapter: postgresql

development:
  <<: *default
  database: ntsb-alerts_development

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql:///ntsb-alerts_test" } %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
    url: <%= ENV["DATABASE_URL"] && URI(ENV["DATABASE_URL"]).tap { |u| u.path += "_cache" } %>
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
    url: <%= ENV["DATABASE_URL"] && URI(ENV["DATABASE_URL"]).tap { |u| u.path += "_queue" } %>
  cable:
    <<: *default
    migrations_paths: db/cable_migrate
    url: <%= ENV["DATABASE_URL"] && URI(ENV["DATABASE_URL"]).tap { |u| u.path += "_cable" } %>
